{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nodepool-annotater.fullname" . }}-clusterrole
  namespace: {{ template "nodepool-annotater.namespace" . }}
  labels:
    {{- include "nodepool-annotater.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - patch
  - watch
- apiGroups:
  - "kube.cloud.ovh.com"
  resources:
  - nodepools
  verbs:
  - get
  - list
  - update
  - patch
  - watch
{{- end }}
