{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodepool-annotater.serviceAccountName" . }}
  namespace: {{ template "nodepool-annotater.namespace" . }}
  labels:
    {{- include "nodepool-annotater.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
